### ISSUE TITLE
fatal error: zmq.h: No such file or directory

### ISSUE THREAD

**Issue by tcfuji** [dato-code/Dato-Core#4]
Getting the following error:

`Dato-Core/src/fault/sockets/async_request_socket.hpp:21:17: fatal error: zmq.h: No such file or directory`

I'm using OS X 10.10 and installed gcc and zeromq using Homebrew.

**Comment by rbkreisberg** [comment]
The build should work nicely with clang, rather than gcc.  Do you have XCode 6 and the XCode 6 command line tools installed?

installing zeromq shouldn't be necessary.  The cmake configure stage should download the dependency.

can you verify that this directory was created:
*Dato-Core/deps/zeromq*

if so, can you verify this file: 
*Dato-Core/deps/zeromq/src/zeromq/include/zmq.h*

**Comment by tcfuji** [comment]
Yes, the zmq.h file exists.

How should I use clang instead of gcc? Would it be enough to simply execute `brew unlink gcc`?

**Comment by ylow** [comment]
Remove the build directories, (release, debug) and the deps directory.

And run:
```
    ./configure --mac_clang
```

We probably should default to clang on the mac instead of gcc.

**Comment by tcfuji** [comment]
Now I'm getting this error:
```
[ 22%] Performing configure step for 'zeromq'
autogen.sh: error: could not find autoreconf.  autoconf and automake are required to run autogen.sh.
make[2]: *** [../deps/zeromq/src/zeromq-stamp/zeromq-configure] Error 1
make[1]: *** [CMakeFiles/zeromq.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ylow** [comment]
Can you try installing
```
    brew install automake
    brew install autoconf
```

**Comment by tcfuji** [comment]
Getting the following after installing mixpanel:
```
$ nosetests
E
======================================================================
ERROR: Failure: ImportError (No module named librato)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tcf/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/tcf/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/tcf/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/debug/src/unity/python/graphlab/__init__.py", line 27, in <module>
    import graphlab.connect.aws as aws
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/debug/src/unity/python/graphlab/connect/__init__.py", line 24, in <module>
    from graphlab_util.metric_tracker import MetricTracker as _MetricTracker
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/debug/src/unity/python/graphlab_util/metric_tracker.py", line 22, in <module>
    import librato
ImportError: No module named librato

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```
Where can I find the librato package?

**Comment by znation** [comment]
@tcfuji The dependencies are defined in [setup.py](https://github.com/dato-code/Dato-Core/blob/master/src/unity/python/setup.py). I will change the README to reflect running setup.py to pull in dependencies, before running unit tests. In the meantime, you can `pip install librato-metrics` to get this module.

**Comment by tcfuji** [comment]
Did the nosetests again and now I'm getting errors because I don't have the product key. Is it absolutely necessary?

**Comment by znation** [comment]
@tcfuji The product key should not be necessary. We are looking into it now.

**Comment by TobyRoseman** [comment]
Hi @tcfuji - I've confirmed that this is a problem. We did setup dato-core not to validate product keys. However it seems our python layer is still expecting a product key value to be present. I apologize for this problem and I'll make sure it gets fixed soon.

As a temporary workaround, you can just set the product key to any non-empty string and dato-core will work fine. Just run ```export GRAPHLAB_PRODUCT_KEY='1' ``` and the unit tests will work fine.

**Comment by tcfuji** [comment]
Thanks @TobyRoseman.

Now I'm getting the following:
```
ERROR: Failure: ImportError (No module named cy_ipc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tcf/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/tcf/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/tcf/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/src/unity/python/graphlab/__init__.py", line 27, in <module>
    import graphlab.connect.aws as aws
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/src/unity/python/graphlab/connect/aws/__init__.py", line 25, in <module>
    from _ec2 import get_credentials, launch_EC2, list_instances, set_credentials, status, terminate_EC2
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/src/unity/python/graphlab/connect/aws/_ec2.py", line 33, in <module>
    import graphlab.connect.server as glserver
  File "/Users/tcf/MEGAsync/code/gitStuff/Dato-Core/src/unity/python/graphlab/connect/server.py", line 22, in <module>
    from graphlab.cython.cy_ipc import PyCommClient as Client
ImportError: No module named cy_ipc

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```
Does it matter if I'm using the Anaconda distribution?

**Comment by TobyRoseman** [comment]
@tcfuji Does this also happen when you ```pip install graphlab-create``` and try to ```import graphlab```?
